# Generated by Django 4.2.7 on 2026-03-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
    ]
